# Generated by Django 4.0 on 2022-01-07 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('Title', models.CharField(max_length=200)),
                ('Discription', models.TextField(blank=True, null=True)),
                ('Demo_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('Source_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
